# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go module dependencies
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 10
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:00"
    # Group minor and patch updates
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "go"
  # GitHub Actions
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "tuesday"
      time: "11:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "github-actions"
