{{- if and .Values.serviceAccount.create  (eq .Values.serviceAccount.permissionScope "namespace") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "reporter.fullname" . }}
  labels:
    {{- include "reporter.labels" . | nindent 4 }}

subjects:
- kind: ServiceAccount
  name: {{ include "reporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "reporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}