baseURL: 'https://docs.kosli.com'
languageCode: 'en-us'
title: 'Kosli developer documentation'

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 2
  goldmark:
    extensions:
      typographer: false
    renderer:
      unsafe: true
  # blackFriday:
  #   smartDashes: false
  # defaultMarkdownHandler: blackFriday

Params:
  BookSection: '/'
  BookToC: true
  default_social_thumb: /kosli-logo-dark-main.svg

caches:
  getjson:
    dir: :cacheDir/:project
    maxAge: 30s

module:
  imports:
  - path: github.com/alex-shpak/hugo-book