baseURL: 'https://docs.kosli.com'
languageCode: 'en-us'
title: 'Kosli developer documentation'

theme: "hugo-book"

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 2
  goldmark:
    extensions:
      typographer: false
    renderer:
      unsafe: true
  # blackFriday:
  #   smartDashes: false
  # defaultMarkdownHandler: blackFriday

Params:
  BookSection: '/'
  BookToC: true
  default_social_thumb: /kosli-docs-logo-white.svg

caches:
  getjson:
    dir: :cacheDir/:project
    maxAge: 30s
