name: "Send CI failure slack message"
description: "Send slack message on failed CI run"
author: "Tore Hagen"

inputs:
  slack_url:
    description: "Slack webhook URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set short SHA
      id: short_sha
      shell: bash
      run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Get failed jobs
      id: failed_jobs
      shell: bash
      run: |
        jobs=$(gh api repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs \
          --jq '.jobs[] | select(.conclusion=="failure") | "- <https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/job/\(.id)|\(.name)>"' \
          | paste -sd "\n" -)
        echo "jobs<<EOF" >> $GITHUB_OUTPUT
        echo "$jobs" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Slack Notification on Failure
      uses: .github/actions/send-slack-message
      with:
        slack_url: ${{ inputs.slack_url }}
        plain_text_preview: ${{ github.workflow }} faild in ${GITHUB_REPOSITORY}
        message: |
          <https://github.com/${GITHUB_REPOSITORY}|${GITHUB_REPOSITORY}> failed in ${{ github.workflow }} <https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}|${{ steps.short_sha.outputs.sha }}>
          <https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|Failed workflow action>
          Failed jobs:
          ${{ steps.failed_jobs.outputs.jobs }}
