# Default values for k8s-reporter. 
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- the kosli reporter image repository
  repository: ghcr.io/kosli-dev/cli
  # -- the kosli reporter image pull policy
  pullPolicy: IfNotPresent
  # -- the kosli reporter image tag, overrides the image tag whose default is the chart appVersion.
  tag: "v2.11.27"

# -- overrides the name used for the created k8s resources. If `fullnameOverride` is provided, it has higher precedence than this one
nameOverride: ""
# -- overrides the fullname used for the created k8s resources. It has higher precedence than `nameOverride`
fullnameOverride: ""

serviceAccount:
  # -- specifies whether a service account should be created
  create: true
  # -- specifies whether to create a cluster-wide permissions for the service account or namespace-scoped permissions. allowed values are: [cluster, namespace]
  permissionScope: cluster
  # -- annotations to add to the service account
  annotations: {}
  # -- the name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- the cron schedule at which the reporter is triggered to report to Kosli  
cronSchedule: "*/5 * * * *"

# -- custom labels to add to pods
podLabels: {}

kosliApiToken:
  # -- the name of the secret containing the kosli API token
  secretName: "kosli-api-token"
  # -- the name of the key in the secret data which contains the Kosli API token
  secretKey: "key"

reporterConfig:
  # -- the name of the Kosli org
  kosliOrg: ""
  # -- the name of Kosli environment that the k8s cluster/namespace correlates to
  kosliEnvironmentName: ""
  # -- the namespaces to scan and report.
  # Cannot be combined with excludeNamespaces or excludeNamespacesRegex.
  # It is a comma separated list of namespace names.
  # Leave this and namespacesRegex unset if you want to report what is running in the entire cluster
  namespaces: ""
  # -- the namespaces Regex patterns to scan and report.
  # Does not have effect if namespaces is set.
  # Requires cluster-wide permissions.
  # Cannot be combined with excludeNamespaces or excludeNamespacesRegex.
  # It is a comma separated list of namespace regex patterns.
  # Leave this and namespaces unset if you want to report what is running in the entire cluster
  namespacesRegex: ""
  # -- the namespaces to exclude from scanning and reporting.
  # Cannot be combined with namespaces or namespacesRegex.
  # It is a comma separated list of namespace names.
  # Leave this and excludeNamespacesRegex unset if you want to report what is running in the entire cluster
  excludeNamespaces: ""
  # -- the namespaces Regex patterns to exclude from scanning and reporting.
  # Does not have effect if excludeNamespaces is set.
  # Cannot be combined with namespaces or namespacesRegex.
  # Requires cluster-wide permissions.
  # It is a comma separated list of namespace regex patterns.
  # Leave this and excludeNamespaces unset if you want to report what is running in the entire cluster
  excludeNamespacesRegex: ""
  # -- whether the dry run mode is enabled or not. In dry run mode, the reporter logs the reports to stdout and does not send them to kosli.
  dryRun: false
  # -- the http proxy url
  httpProxy: ""

  # -- the security context for the reporter cronjob
  # Set to null or {} to disable security context entirely (not recommended)
  # For OpenShift, you can omit runAsUser to let OpenShift assign the UID
  securityContext:
    # -- whether to allow privilege escalation
    allowPrivilegeEscalation: false
    # -- whether to run as non root
    runAsNonRoot: true
    # -- the user id to run as
    # Omit this field for OpenShift environments to allow automatic UID assignment
    runAsUser: 1000

# Uncomment the env variable below and replace <instance_name>, if you are on a single tenant Kosli instance
# env:
#   KOSLI_HOST: https://<instance_name>.kosli.com

# -- any custom annotations to be added to the cronjob
podAnnotations: {}

resources: 
  requests:
    # -- the memory request
    memory: "64Mi"
  limits:
    # -- the memory limit
    memory: "256Mi"
    # -- the cpu limit
    cpu: "100m"