name: Send Slack Message
description: Send Slack Message to a SLACK URL

inputs:
  plain_text_preview:
    description: Plain text preview (on mobile devices for instance)
    required: true
  message:
    description: Slack message to send
    required: true
  slack_url:
    description: Slack URL to send message to
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Slack Message
      shell: bash
      run: |
          MESSAGE=$(cat <<EOF
          {
             "text": "${{ inputs.plain_text_preview }}",
             "blocks": [
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
                   "text": "${{ inputs.message }}"
                 }
               }
             ]
          }
          EOF
          )
          curl -X POST \
            -H 'Content-type: application/json' \
            --data "${MESSAGE}" \
            --fail \
            "${{ inputs.slack_url }}"
