name: Upload Kosli cli lambda layer

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string

jobs:
  upload-layer:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/cli
          aws-region: ${{ inputs.AWS_REGION }}
          role-duration-seconds: 2400
          role-session-name: ${{ github.event.repository.name }}

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Upload reporter lambda package
        id: upload-reporter-lambda-package
        env:
          TAG: ${{ inputs.tag }}
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
        run: ./bin/upload_cli_layer.sh
